/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.util.Observable;
import java.util.Observer;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTable;

/**
 *
 * @author erick
 */
public class VistaOperacionesMatrices extends javax.swing.JFrame{

    /**
     * Creates new form VistaOperacionesMatrices
     */
    
    
    public VistaOperacionesMatrices(){
        initComponents();
        getjComboBoxColumnas().setEnabled(false);
        getjComboBoxFilas().setEnabled(false);
        getjButtonLimpiar().setEnabled(false);
        getjButtonEstablecer().setEnabled(false);
        getjButtonResultado().setEnabled(false);
    }

    public JTable getjTableMatriz1() {
        return jTableMatriz1;
    }

    public void setjTableMatriz1(JTable jTableMatriz1) {
        this.jTableMatriz1 = jTableMatriz1;
    }

    public JTable getjTableMatriz2() {
        return jTableMatriz2;
    }

    public void setjTableMatriz2(JTable jTableMatriz2) {
        this.jTableMatriz2 = jTableMatriz2;
    }

    public JTable getjTableResultados() {
        return jTableResultados;
    }

    public void setjTableResultados(JTable jTableResultados) {
        this.jTableResultados = jTableResultados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonSuma = new javax.swing.JButton();
        jButtonMultipEscalar = new javax.swing.JButton();
        jButtonMultiplicación = new javax.swing.JButton();
        jButtonInversa = new javax.swing.JButton();
        jButtonDeterminante = new javax.swing.JButton();
        jButtonSolucionCramer = new javax.swing.JButton();
        jButtonSolucionGauss = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxFilas = new javax.swing.JComboBox();
        jComboBoxColumnas = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jPanelMatriz1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMatriz1 = new javax.swing.JTable();
        jPanelMatriz2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMatriz2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jPanelResultado = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableResultados = new javax.swing.JTable();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonResultado = new javax.swing.JButton();
        jButtonEstablecer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("OPERACIONES");

        jButtonSuma.setText("Suma de Matrices");

        jButtonMultipEscalar.setText("Multiplicación de una matriz por un escalar");
        jButtonMultipEscalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultipEscalarActionPerformed(evt);
            }
        });

        jButtonMultiplicación.setText("Multiplicación de matrices");

        jButtonInversa.setText("Inversa de una matriz por Gauss-Jordan");

        jButtonDeterminante.setText("Determinante de una matriz");

        jButtonSolucionCramer.setText("Solución de un sistema de ecuaciones por el método de Cramer");

        jButtonSolucionGauss.setText("Solución de un sistema de ecuaciones por el método de Gauss-Jordan");

        jLabel2.setText("Filas");

        jComboBoxFilas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "2", "3", "4", "5" }));

        jComboBoxColumnas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "2", "3", "4", "5" }));

        jLabel3.setText("Columnas");

        jTableMatriz1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableMatriz1);

        javax.swing.GroupLayout jPanelMatriz1Layout = new javax.swing.GroupLayout(jPanelMatriz1);
        jPanelMatriz1.setLayout(jPanelMatriz1Layout);
        jPanelMatriz1Layout.setHorizontalGroup(
            jPanelMatriz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
        );
        jPanelMatriz1Layout.setVerticalGroup(
            jPanelMatriz1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );

        jTableMatriz2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableMatriz2);

        javax.swing.GroupLayout jPanelMatriz2Layout = new javax.swing.GroupLayout(jPanelMatriz2);
        jPanelMatriz2.setLayout(jPanelMatriz2Layout);
        jPanelMatriz2Layout.setHorizontalGroup(
            jPanelMatriz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
        );
        jPanelMatriz2Layout.setVerticalGroup(
            jPanelMatriz2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
        );

        jLabel4.setText("Resultado");

        jTableResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableResultados);

        javax.swing.GroupLayout jPanelResultadoLayout = new javax.swing.GroupLayout(jPanelResultado);
        jPanelResultado.setLayout(jPanelResultadoLayout);
        jPanelResultadoLayout.setHorizontalGroup(
            jPanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
        );
        jPanelResultadoLayout.setVerticalGroup(
            jPanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
        );

        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonResultado.setText("Ver resultado");

        jButtonEstablecer.setText("Establecer matriz");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jButtonSolucionGauss, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jButtonMultiplicación, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jButtonMultipEscalar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                            .addComponent(jButtonSuma, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(68, 68, 68))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jButtonInversa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jButtonDeterminante, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addComponent(jPanelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(jButtonLimpiar))
                                    .addComponent(jPanelMatriz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBoxFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBoxColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(85, 85, 85)
                                        .addComponent(jButtonEstablecer))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(48, 48, 48)
                                        .addComponent(jPanelMatriz2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jButtonSolucionCramer, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(202, 202, 202)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonResultado)
                            .addComponent(jLabel4))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jComboBoxFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBoxColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jButtonEstablecer)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSuma)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMultipEscalar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMultiplicación)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInversa)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeterminante)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSolucionCramer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanelMatriz2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelMatriz1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jButtonSolucionGauss)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonResultado)
                        .addGap(18, 18, 18)))
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanelResultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpiar)
                        .addGap(63, 63, 63))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMultipEscalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultipEscalarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMultipEscalarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    public void setjPanelMatriz1(JPanel jPanelMatriz1) {
        this.jPanelMatriz1 = jPanelMatriz1;
    }

    public void setjPanelMatriz2(JPanel jPanelMatriz2) {
        this.jPanelMatriz2 = jPanelMatriz2;
    }

    public void setjPanelResultado(JPanel jPanelResultado) {
        this.jPanelResultado = jPanelResultado;
    }

    public JButton getjButtonDeterminante() {
        return jButtonDeterminante;
    }

    public JButton getjButtonEstablecer() {
        return jButtonEstablecer;
    }

    public JButton getjButtonInversa() {
        return jButtonInversa;
    }

    public JButton getjButtonLimpiar() {
        return jButtonLimpiar;
    }

    public JButton getjButtonMultipEscalar() {
        return jButtonMultipEscalar;
    }

    public JButton getjButtonMultiplicación() {
        return jButtonMultiplicación;
    }

    public JButton getjButtonResultado() {
        return jButtonResultado;
    }

    public JButton getjButtonSolucionCramer() {
        return jButtonSolucionCramer;
    }

    public JButton getjButtonSolucionGauss() {
        return jButtonSolucionGauss;
    }

    public JButton getjButtonSuma() {
        return jButtonSuma;
    }

    public JComboBox getjComboBoxColumnas() {
        return jComboBoxColumnas;
    }

    public JComboBox getjComboBoxFilas() {
        return jComboBoxFilas;
    }

    public JPanel getjPanelMatriz1() {
        return jPanelMatriz1;
    }

    public JPanel getjPanelMatriz2() {
        return jPanelMatriz2;
    }

    public JPanel getjPanelResultado() {
        return jPanelResultado;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaOperacionesMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaOperacionesMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaOperacionesMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaOperacionesMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaOperacionesMatrices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeterminante;
    private javax.swing.JButton jButtonEstablecer;
    private javax.swing.JButton jButtonInversa;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonMultipEscalar;
    private javax.swing.JButton jButtonMultiplicación;
    private javax.swing.JButton jButtonResultado;
    private javax.swing.JButton jButtonSolucionCramer;
    private javax.swing.JButton jButtonSolucionGauss;
    private javax.swing.JButton jButtonSuma;
    private javax.swing.JComboBox jComboBoxColumnas;
    private javax.swing.JComboBox jComboBoxFilas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanelMatriz1;
    private javax.swing.JPanel jPanelMatriz2;
    private javax.swing.JPanel jPanelResultado;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableMatriz1;
    private javax.swing.JTable jTableMatriz2;
    private javax.swing.JTable jTableResultados;
    // End of variables declaration//GEN-END:variables

    
}
