/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import java.awt.Color;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author erick
 */
public final class VistaOperacionesMatrices extends javax.swing.JFrame{

    /**
     * Creates new form VistaOperacionesMatrices
     */
    
    
    @SuppressWarnings("empty-statement")
    public VistaOperacionesMatrices(){
        initComponents();
        getjComboBoxColumnas().setEnabled(false);
        getjComboBoxFilas().setEnabled(false);
        getjButtonLimpiar().setEnabled(false);
        getjButtonEstablecer().setEnabled(false);
        getjButtonResultado().setEnabled(false);
        getjButtonLimpiarMatriz().setEnabled(false);
        
        getjButtonDeterminante().setBackground(Color.LIGHT_GRAY);
        getjButtonInversa().setBackground(Color.LIGHT_GRAY);        
        getjButtonMultipEscalar().setBackground(Color.LIGHT_GRAY);;
       getjButtonMultiplicación().setBackground(Color.LIGHT_GRAY);;       
        getjButtonSolucionCramer().setBackground(Color.LIGHT_GRAY);;
        getjButtonSolucionGauss().setBackground(Color.LIGHT_GRAY);;
        getjButtonSuma().setBackground(Color.LIGHT_GRAY);
    }

    public JTable getjTableMatriz1() {
        return jTableMatriz1;
    }

    public void setjTableMatriz1(JTable jTableMatriz1) {
        this.jTableMatriz1 = jTableMatriz1;
    }

    public JTable getjTableMatriz2() {
        return jTableMatriz2;
    }

    public void setjTableMatriz2(JTable jTableMatriz2) {
        this.jTableMatriz2 = jTableMatriz2;
    }

    public JTable getjTableResultados() {
        return jTableResultados;
    }

    public void setjTableResultados(JTable jTableResultados) {
        this.jTableResultados = jTableResultados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonSuma = new javax.swing.JButton();
        jButtonMultipEscalar = new javax.swing.JButton();
        jButtonMultiplicación = new javax.swing.JButton();
        jButtonInversa = new javax.swing.JButton();
        jButtonDeterminante = new javax.swing.JButton();
        jButtonSolucionCramer = new javax.swing.JButton();
        jButtonSolucionGauss = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxFilas = new javax.swing.JComboBox();
        jComboBoxColumnas = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonResultado = new javax.swing.JButton();
        jButtonEstablecer = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableMatriz1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableResultados = new javax.swing.JTable();
        jLabelOperador = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableMatriz2 = new javax.swing.JTable();
        jButtonLimpiarMatriz = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("OPERACIONES");

        jButtonSuma.setText("Suma de Matrices");

        jButtonMultipEscalar.setText("Mult. por escalar");
        jButtonMultipEscalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultipEscalarActionPerformed(evt);
            }
        });

        jButtonMultiplicación.setText("Mult de matrices");

        jButtonInversa.setText("Inversa");

        jButtonDeterminante.setText("Determinante");

        jButtonSolucionCramer.setText("Solución Cramer");

        jButtonSolucionGauss.setText("Solución Gauss");

        jLabel2.setText("Filas");

        jComboBoxFilas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "2", "3", "4", "5" }));

        jComboBoxColumnas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--", "2", "3", "4", "5" }));

        jLabel3.setText("Columnas");

        jLabel4.setText("Resultado");

        jButtonLimpiar.setText("Terminar");
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonResultado.setText("Ver resultado");

        jButtonEstablecer.setText("Establecer matriz");

        jTableMatriz1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableMatriz1);

        jTableResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(jTableResultados);

        jLabelOperador.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTableMatriz2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTableMatriz2);

        jButtonLimpiarMatriz.setText("Limpiar Matrices");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(163, 163, 163)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jButtonEstablecer))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonSuma, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                                .addComponent(jButtonMultipEscalar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonMultiplicación, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonInversa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSolucionCramer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSolucionGauss, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonDeterminante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(jButtonLimpiar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(jLabelOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jButtonResultado)
                                        .addGap(52, 52, 52))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(35, 35, 35)))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(82, 82, 82)
                                .addComponent(jButtonLimpiarMatriz)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jComboBoxFilas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxColumnas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jButtonEstablecer))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(305, 305, 305)
                                .addComponent(jButtonLimpiarMatriz)
                                .addGap(135, 135, 135))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(119, 119, 119)
                                        .addComponent(jLabelOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButtonResultado)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel4))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(38, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jButtonSuma)))
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMultipEscalar)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMultiplicación)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonInversa)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSolucionCramer, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSolucionGauss)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDeterminante)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonLimpiar)
                        .addGap(69, 69, 69))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMultipEscalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultipEscalarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonMultipEscalarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonLimpiarActionPerformed


    public JButton getjButtonDeterminante() {
        return jButtonDeterminante;
    }

    public JButton getjButtonEstablecer() {
        return jButtonEstablecer;
    }

    public JButton getjButtonInversa() {
        return jButtonInversa;
    }

    public JButton getjButtonLimpiar() {
        return jButtonLimpiar;
    }

    public JLabel getjLabelOperador() {
        return jLabelOperador;
    }

    public JButton getjButtonMultipEscalar() {
        return jButtonMultipEscalar;
    }

    public JButton getjButtonMultiplicación() {
        return jButtonMultiplicación;
    }

    public JButton getjButtonResultado() {
        return jButtonResultado;
    }

    public JButton getjButtonSolucionCramer() {
        return jButtonSolucionCramer;
    }

    public JButton getjButtonSolucionGauss() {
        return jButtonSolucionGauss;
    }

    public JButton getjButtonSuma() {
        return jButtonSuma;
    }

    public JComboBox getjComboBoxColumnas() {
        return jComboBoxColumnas;
    }

    public JComboBox getjComboBoxFilas() {
        return jComboBoxFilas;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaOperacionesMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaOperacionesMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaOperacionesMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaOperacionesMatrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VistaOperacionesMatrices().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDeterminante;
    private javax.swing.JButton jButtonEstablecer;
    private javax.swing.JButton jButtonInversa;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonLimpiarMatriz;
    private javax.swing.JButton jButtonMultipEscalar;
    private javax.swing.JButton jButtonMultiplicación;
    private javax.swing.JButton jButtonResultado;
    private javax.swing.JButton jButtonSolucionCramer;
    private javax.swing.JButton jButtonSolucionGauss;
    private javax.swing.JButton jButtonSuma;
    private javax.swing.JComboBox jComboBoxColumnas;
    private javax.swing.JComboBox jComboBoxFilas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelOperador;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableMatriz1;
    private javax.swing.JTable jTableMatriz2;
    private javax.swing.JTable jTableResultados;
    // End of variables declaration//GEN-END:variables

    public JButton getjButtonLimpiarMatriz() {
        return jButtonLimpiarMatriz;
    }

    public JScrollPane getjScrollPane3() {
        return jScrollPane3;
    }

    
}
